FROM python:3.12.6-slim

ENV PIPENV_VENV_IN_PROJECT=1

# pipenv - npm for python
RUN pip install pipenv

# non-root user
RUN useradd -ms /bin/bash my-user

# estabeleco o usuario padrao da imagem/container
USER my-user

WORKDIR /app

#RUN chown -R my-user /app

COPY --chown=my-user:my-user . /app

RUN chmod +x /app/start.sh

RUN pipenv install

# comando que será executado ao iniciar o container
CMD sh -c /app/start.sh